### ISSUE TITLE
picks wrong version with --pretend?

### ISSUE THREAD

**Issue by svenfuchs** [svenfuchs/gem-release#75] opened 2018-06-21 11:52 UTC
```
$ gem bump -v patch --tag --push --pretend

Bumping travis-conditions from version 1.0.0-dev.2 to 1.0.0
Staging lib/travis/conditions/version.rb
$ git add lib/travis/conditions/version.rb

Creating commit
$ git commit -m "Bump travis-conditions to 1.0.0"

Pushing to the origin git repository
$ git push origin

Tagging travis-conditions as version 1.0.0.pre.dev.2
Creating git tag v1.0.0.pre.dev.2
$ git tag -am "tag v1.0.0.pre.dev.2" v1.0.0.pre.dev.2

Pushing tags to the origin git repository
$ git push --tags origin

All is good, thanks my friend.
```

**Comment by PikachuEXE** [comment] 2019-06-26 06:53
Duplicate of #79 
Should be partially fixed by #83

**Closed by PikachuEXE** 2019-06-26 06:53 UTC
